# for dev
name: pull request CI

on:
  pull_request:
    branches: [master]

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd apps/client && pwd
      - run: pwd && npm ci
      - run: pwd npm run test
      - run: npm run build
      - run: npm run deploy-prod
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
