# for production
# for dev
name: push to master CI

on:
  push:
    branches: [master]

jobs:
  build-deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd apps/client && npm ci
      - run: cd apps/client && npm run test-ci
      - run: cd apps/client && npm run build
      - run: cd apps/client && npm run deploy-prod
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
